//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int id { get; set; }
        public string p_fName { get; set; }
        public string p_lName { get; set; }
        public string p_faName { get; set; }
        public string p_idcard { get; set; }
    }
}
